name: CI/CD for FastAPI

on:
  push:
    branches:
      -main
jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    -name: checkout repository
    uses: actions/checkout@v2
    
    -name: set up python
    uses: actions/checkout@v2
    with:
      python-version: 3.x

    
